name: Deploy BarberYass to Firebase Hosting

on:
  push:
    branches:
      - main  # Cada vez que hagas push a main se desplegará

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Build de Vite
        run: npm run build

      - name: Deploy a Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BARBERYASS }}"
          channelId: live
          projectId: barberyass
